from typing import TypedDict, List, Annotated, Optional
import operator

class AgentOpsState(TypedDict):
    # Unique task identifier
    task_id: str
    
    # Original user prompt or issue description
    task_description: str
    
    # Code context retrieved or provided
    code_context: str
    
    # Code generated by Developer Agent
    generated_code: str
    
    # Execution outputs and logs from Docker Sandbox
    execution_logs: str
    
    # Validation status flags
    test_passed: bool
    human_approved: Optional[bool]
    
    # Message history across agent transitions (append-only)
    messages: Annotated[List[dict], operator.add]
